name: 自动化构建Docker镜像

on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v4
        name: Build & push Docker image
        with:
          image: icaruz/faka
          tag: v1.8
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


  # DEV版暂停阿里云推送
  # push_to_aliyun:
  #   name: Push Docker image to Aliyun Hub
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2.3.2
  #       name: Check out code

  #     - uses: mr-smithers-excellent/docker-build-push@v4
  #       name: Build & push Docker image
  #       with:
  #         image: baiyuetribe/kamifaka
  #         tag: latest
  #         registry: registry.cn-hangzhou.aliyuncs.com
  #         username: ${{ secrets.ALIYUN_USERNAME }}
  #         password: ${{ secrets.ALIYUN_PASSWORD }}

      # - name: SSH Remote deploy CN
      #   uses: appleboy/ssh-action@master
      #   with: 
      #     host: 106.14.76.252
      #     username: root
      #     password: ${{ secrets.REMOTE_PASSWORD2 }}
      #     port: 22
      #     script: |
      #       docker rm -f kamifaka
      #       rm -rf /opt/kamifaka
      #       docker rmi -f baiyuetribe/kamifaka
      #       docker run -d --name=kamifaka --restart=always -p 8000:8000 -v /opt/kamifaka:/usr/src/app/public baiyuetribe/kamifaka